#Dictionary
mydict={"brand":"Ford","model":"Mustang","year":1976}
print(mydict)
print(mydict["brand"])
print(type(mydict))
dict2={"a":1,"b":2,"b":6}
print(dict2)
print(len(mydict))
print(len(dict2))
print(mydict.keys())
print(mydict.values())
print(dict2.keys())
print(dict2.values())
thisdict=dict(name="john",age=34)
print(thisdict)
thisdict["age"]=36
print(thisdict)
thisdict.update({"age":39})
print(thisdict)
thisdict["designation"]="Manager"
print(thisdict)
thisdict.pop("designation")
print(thisdict)
thisdict.popitem()
print(thisdict)
thisdict.clear()
print(thisdict)
del thisdict
print(thisdict)

